 

// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DefaultConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=(local);Initial Catalog=WeiCrowdFund;User ID=sa;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using T4GeneratModelUtils;

namespace DefaultConnection
{
	[Alias("AccountDetails")]
    public partial class AccountDetail : IHasId<int> 
    {
        [Alias("AccountDetailId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int AccountId { get; set;}
        [Required]
        public int UserId { get; set;}
        public int? EventType { get; set;}
        public decimal? Amount { get; set;}
        public string Description { get; set;}
        public string IP { get; set;}
        public long? AboutId { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("Accounts")]
    public partial class Account : IHasId<int> 
    {
        [Alias("UserId")]
        [Required]
        public int Id { get; set;}
        public decimal? Balance { get; set;}
        public decimal? LockedBalance { get; set;}
        public decimal? DrawLocked { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("AccountWithDrawals")]
    public partial class AccountWithDrawal : IHasId<int> 
    {
        [Alias("WithDrawId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        [Required]
        public int AdminUserId { get; set;}
        [Required]
        public int UserAccountId { get; set;}
        public decimal? WithDrawAmount { get; set;}
        public int? StatusId { get; set;}
        public DateTime? VerifiedDate { get; set;}
        public decimal? FinallyDrawAmount { get; set;}
        public string IP { get; set;}
        public int? Reason { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("BankBranchs")]
    public partial class BankBranch 
    {
        [Required]
        public int BankBranchId { get; set;}
        public int? ProvinceId { get; set;}
        public int? BankTypeId { get; set;}
        public double? BranchCode { get; set;}
        public string BranchName { get; set;}
        public int? CityId { get; set;}
        public int? DistrictId { get; set;}
        public DateTime? CreationDate { get; set;}
    }
	[Alias("BankTypes")]
    public partial class BankType 
    {
        [Required]
        public int BankTypeId { get; set;}
        public string BankName { get; set;}
        public int? OrderId { get; set;}
        public int? IsDisplay { get; set;}
        public string BankCode { get; set;}
    }
	[Alias("ChatFriendApplications")]
    public partial class ChatFriendApplication : IHasId<int> 
    {
        [Alias("FriendApplyId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int TypeId { get; set;}
        [Required]
        public int OwnerId { get; set;}
        public int? FriendId { get; set;}
        public string Mobile { get; set;}
        public int? StatusId { get; set;}
        [Required]
        public DateTime ModifyDate { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("ChatFriendships")]
    public partial class ChatFriendship : IHasId<int> 
    {
        [Alias("FriendshipId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int OwnerId { get; set;}
        [Required]
        public int FriendId { get; set;}
        public string Notes { get; set;}
        public int? INotSeeHimId { get; set;}
        public int? HeNotSeeMeId { get; set;}
        public int? StatusId { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("ChatGroupNotices")]
    public partial class ChatGroupNotice : IHasId<int> 
    {
        [Alias("GroupNoteId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int GroupId { get; set;}
        public string Title { get; set;}
        public string Content { get; set;}
        public int? StatusId { get; set;}
        public DateTime? ModifyDate { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("ChatGroups")]
    public partial class ChatGroup : IHasId<int> 
    {
        [Alias("GroupId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string EasemobGroupId { get; set;}
        [Required]
        public int UserId { get; set;}
        public string Avatar { get; set;}
        public int? StatusId { get; set;}
        public int? CrowdFundId { get; set;}
        public string GroupName { get; set;}
        public int? MaxUser { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("ChatGroupUsers")]
    public partial class ChatGroupUser : IHasId<int> 
    {
        [Alias("GruopUserId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int GroupId { get; set;}
        [Required]
        public int UserId { get; set;}
        public string NickName { get; set;}
        public int? StatusId { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("Citys")]
    public partial class City : IHasId<int> 
    {
        [Alias("CityId")]
        [Required]
        public int Id { get; set;}
        public string CityName { get; set;}
        public string ZipCode { get; set;}
        public int? ProvinceId { get; set;}
        public string PinYin { get; set;}
        public string Logogram { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("Comments")]
    public partial class Comment : IHasId<int> 
    {
        [Alias("CommentId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int CrowdFundId { get; set;}
        [Required]
        public int CommentUserId { get; set;}
        public int? ReplyUserId { get; set;}
        public string CommentMsg { get; set;}
        public string ReplyMsg { get; set;}
        public int? StatusId { get; set;}
        public DateTime? ModifyDate { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("CrowdFundings")]
    public partial class CrowdFunding : IHasId<int> 
    {
        [Alias("CrowdFundId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        public string Name { get; set;}
        public decimal? TargetAmount { get; set;}
        public string Profile { get; set;}
        public string Content { get; set;}
        [Required]
        public int DueDays { get; set;}
        public string Images { get; set;}
        public string Audios { get; set;}
        public decimal? RaisedAmount { get; set;}
        [Required]
        public int StatusId { get; set;}
        [Required]
        public int TypeId { get; set;}
        [Required]
        public int RecommendSort { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("Districts")]
    public partial class District : IHasId<int> 
    {
        [Alias("DistrictId")]
        [Required]
        public int Id { get; set;}
        public string DistrictName { get; set;}
        public int? CityId { get; set;}
        public int? TypeId { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("Feedbacks")]
    public partial class Feedback : IHasId<int> 
    {
        [Alias("FeedbackId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        public string Content { get; set;}
        public int? ReplyUserId { get; set;}
        public string ReplyContent { get; set;}
        public DateTime? ModifyDate { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("IdentityAuthentication")]
    public partial class IdentityAuthentication : IHasId<int> 
    {
        [Alias("IdentiAuthId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        public int? RealName { get; set;}
        public string IdNumber { get; set;}
        public int? StatusId { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("MessageSetting")]
    public partial class MessageSetting : IHasId<int> 
    {
        [Alias("UserId")]
        [Required]
        public int Id { get; set;}
        public int? IsShowDetails { get; set;}
        public int? MsgTrouble { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("MobileCodes")]
    public partial class MobileCode : IHasId<int> 
    {
        [Alias("MobileCodeId")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Mobile { get; set;}
        public string Code { get; set;}
        public int? CodeTypeId { get; set;}
        public int? StatusId { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("MobileMessages")]
    public partial class MobileMessage : IHasId<int> 
    {
        [Alias("MobileMsgId")]
        [AutoIncrement]
        public int Id { get; set;}
        public int? UserId { get; set;}
        public string Mobile { get; set;}
        public int? TypeId { get; set;}
        public string Contents { get; set;}
        public int? IsSend { get; set;}
        public int? IsTimely { get; set;}
        public int? SmsTypeId { get; set;}
        public string ReplyCode { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("NewBalance")]
    public partial class NewBalance : IHasId<int> 
    {
        [Alias("AccountDetailId")]
        [Required]
        public int Id { get; set;}
        public decimal? Balance { get; set;}
        [Required]
        public DateTime CreationDate { get; set;}
    }
	[Alias("PasswordChangeLog")]
    public partial class PasswordChangeLog : IHasId<int> 
    {
        [Alias("PwdLogId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        public string OldPwd { get; set;}
        public string NewPwd { get; set;}
        public string IP { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("PhoneNums")]
    public partial class PhoneNum : IHasId<int> 
    {
        [Alias("PhoneId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        public string Name { get; set;}
        public string Phone { get; set;}
        public int? StatusId { get; set;}
        [Required]
        public DateTime ModifyDate { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("Provinces")]
    public partial class Province : IHasId<int> 
    {
        [Alias("ProvinceId")]
        [Required]
        public int Id { get; set;}
        public string ProvinceName { get; set;}
        public int? OrderId { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("RechargeLogs")]
    public partial class RechargeLog : IHasId<int> 
    {
        [Alias("RechargeId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        public int? AdminUserId { get; set;}
        [Required]
        public int UserAccountId { get; set;}
        public decimal? RechargeAmount { get; set;}
        public int? StatusId { get; set;}
        public DateTime? VerifiedDate { get; set;}
        public decimal? FinallyRechargeAmount { get; set;}
        public string IP { get; set;}
        public string Reason { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("RepayWays")]
    public partial class RepayWay : IHasId<int> 
    {
        [Alias("RepayId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int CrowdFundId { get; set;}
        [Required]
        public int UserId { get; set;}
        public decimal? SupportAmount { get; set;}
        public string Description { get; set;}
        public string Images { get; set;}
        public int? StatusId { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("ReportLists")]
    public partial class ReportList : IHasId<int> 
    {
        [Alias("ReportId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        public int? TypeId { get; set;}
        public int? ObjectId { get; set;}
        public string Reason { get; set;}
        public int? StatusId { get; set;}
        public DateTime? ModifyDate { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("SupportProjects")]
    public partial class SupportProject : IHasId<int> 
    {
        [Alias("SupportProjectId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        [Required]
        public int CrowdFundId { get; set;}
        public int? RepayId { get; set;}
        public decimal? Amount { get; set;}
        public int? StatusId { get; set;}
        public int? UserAddresId { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("SystemAccountDetails")]
    public partial class SystemAccountDetail : IHasId<int> 
    {
        [Alias("SysAccountDetailId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int SysUserId { get; set;}
        public decimal? Amount { get; set;}
        public decimal? Balance { get; set;}
        public string Description { get; set;}
        public string IP { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("SystemAccounts")]
    public partial class SystemAccount : IHasId<int> 
    {
        [Alias("SysUserId")]
        [Required]
        public int Id { get; set;}
        public decimal? Balance { get; set;}
        public decimal? LockedBalance { get; set;}
        public decimal? DrawLocked { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("SystemMessages")]
    public partial class SystemMessage : IHasId<int> 
    {
        [Alias("SysMsgId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        [Required]
        public int AboutId { get; set;}
        public string Message { get; set;}
        public int? StatusId { get; set;}
        [Required]
        public DateTime CreateDate { get; set;}
    }
	[Alias("SystemUsers")]
    public partial class SystemUser : IHasId<int> 
    {
        [Alias("SysUserId")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Name { get; set;}
        public string Description { get; set;}
        public int? TypeId { get; set;}
        public int? StatusId { get; set;}
        [Required]
        public DateTime CreationDate { get; set;}
    }
	[Alias("ThirdPartyUsers")]
    public partial class ThirdPartyUser : IHasId<int> 
    {
        [Alias("TPUserId")]
        [AutoIncrement]
        public int Id { get; set;}
        public int? UserId { get; set;}
        [Required]
        public int OpenId { get; set;}
        public int? NickName { get; set;}
        public int? Sex { get; set;}
        public string Province { get; set;}
        public string City { get; set;}
        public string Avatar { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("UserAccounts")]
    public partial class UserAccount : IHasId<int> 
    {
        [Alias("UserAccountId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int TypeId { get; set;}
        [Required]
        public int UserId { get; set;}
        public string RealName { get; set;}
        public int? StatusId { get; set;}
        public int? BankTypeId { get; set;}
        public string AccountNum { get; set;}
        public int? DistrictId { get; set;}
        public string BranchName { get; set;}
        public int? BranchId { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("UserActivitys")]
    public partial class UserActivity : IHasId<int> 
    {
        [Alias("UserActivityId")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int UserId { get; set;}
        public int? Action { get; set;}
        public int? EventTypeId { get; set;}
        public string Description { get; set;}
        public string IP { get; set;}
        public DateTime? CreationDate { get; set;}
    }
	[Alias("UserAddressList")]
    public partial class UserAddressList : IHasId<int> 
    {
        [Alias("UserAddresId")]
        [AutoIncrement]
        public int Id { get; set;}
        public string UserId { get; set;}
        public int? DistrictId { get; set;}
        public string RecvName { get; set;}
        public string Mobile { get; set;}
        public string Details { get; set;}
        public string ZipCode { get; set;}
        public int? StatusId { get; set;}
        public DateTime? ModifyDate { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("UserDetails")]
    public partial class UserDetail : IHasId<int> 
    {
        [Alias("UserId")]
        [Required]
        public int Id { get; set;}
        public int? Sex { get; set;}
        public string RealName { get; set;}
        public string IdNumber { get; set;}
        public string Occupation { get; set;}
        public string School { get; set;}
        public string Company { get; set;}
        public int? DistrictId { get; set;}
        public string Address { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("UserLoginLog")]
    public partial class UserLoginLog : IHasId<int> 
    {
        [Alias("LoginId")]
        [AutoIncrement]
        public int Id { get; set;}
        public string Mobile { get; set;}
        public int? Password { get; set;}
        public int? StatusId { get; set;}
        public int? CreateDate { get; set;}
    }
	[Alias("Users")]
    public partial class User : IHasId<int> 
    {
        [Alias("UserId")]
        [AutoIncrement]
        public int Id { get; set;}
        public string UserName { get; set;}
        public string NickName { get; set;}
        public string Avatar { get; set;}
        public string Signature { get; set;}
        public string Password { get; set;}
        public string Mobile { get; set;}
        public string Email { get; set;}
        [Required]
        public int StatusId { get; set;}
        public int? FromId { get; set;}
        public DateTime? LastLoginDate { get; set;}
        public DateTime? CreateDate { get; set;}
    }
	[Alias("UserValidates")]
    public partial class UserValidate : IHasId<int> 
    {
        [Alias("UserId")]
        [Required]
        public int Id { get; set;}
        public int? IdValidate { get; set;}
        public DateTime? IdValidateDate { get; set;}
        public int? PhoneValidate { get; set;}
        public DateTime? PhoneValidateDate { get; set;}
        public int? VideoValidate { get; set;}
        public DateTime? VideoValidateDate { get; set;}
        public int? EmailValidate { get; set;}
        public DateTime? EmailValidateDate { get; set;}
        public int? EducationValidate { get; set;}
        public DateTime? EducationValidateDate { get; set;}
        public DateTime? CreationDate { get; set;}
    }
}
#pragma warning restore 1591
